# Use official Python image as base
FROM python:3.10-slim

# Set working directory in container
WORKDIR /app

# Copy script into container
COPY app.py .

# Set the default command to run
CMD ["python", "app.py"]